CREATE DATABASE RFID;

USE RFID;

CREATE TABLE Usuario(
	ID VARCHAR(50) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE Acceso(
	ID INT NOT NULL AUTO_INCREMENT,
    idUsuario VARCHAR(50) NOT NULL,
    fechatiempo DATETIME NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (idUsuario) REFERENCES Usuario(ID)
);
